name: build garden linux container
on:
  workflow_call:
env:
  IMAGE_NAME: gardenlinux/integration-test
jobs:
  build_container:
    name: make container
    runs-on: ec2-gardenlinux-amd64
    strategy:
      matrix:
        # TODO: add integration-test to targets before PR
        target: [ packagebuild ]
    steps:
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u $ --password-stdin

      - name: make test container
        run: make --directory=container build-${{ matrix.target }}

      - name: Set VERSION from garden-version
        run: echo "VERSION=$(bin/garden-version)" >> $GITHUB_ENV
      
      - name: Set VERSION_DATE from garden-version
        run: echo "VERSION_DATE=$(bin/garden-version --date)" >> $GITHUB_ENV

      - name: Set VERSION_FULL from garden-version
        run: echo "VERSION_FULL=$(bin/garden-version --major).$(bin/garden-version --minor)" >> $GITHUB_ENV

      - name: upload container to ghcr.io
        run: |
          sudo podman tag "gardenlinux/${{ matrix.target }}:${{ env.VERSION }}" "ghcr.io/gardenlinux/gardenlinux/${{ matrix.target }}:${{ env.VERSION }}"
          sudo podman tag "gardenlinux/${{ matrix.target }}:${{ env.VERSION_DATE }}" "ghcr.io/gardenlinux/gardenlinux/${{ matrix.target }}:${{ env.VERSION_DATE }}"
          sudo podman tag "gardenlinux/${{ matrix.target }}:${{ env.VERSION_FULL }}" "ghcr.io/gardenlinux/gardenlinux/${{ matrix.target }}:${{ env.VERSION_FULL }}"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/${{ matrix.target }}:${{ env.VERSION }}"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/${{ matrix.target }}:${{ env.VERSION_DATE }}"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/${{ matrix.target }}:${{ env.VERSION_FULL }}"
