name: build garden linux container
on:
  workflow_call:
env:
  IMAGE_NAME: gardenlinux/integration-test
jobs:
  build_container:
    name: make container
    runs-on: ec2-gardenlinux-amd64
    strategy:
      matrix:
        target: [ integration-test, packagebuild]
    steps:
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u $ --password-stdin

      - name: make test container
        run: make --directory=container build-$target

      - name: upload container to ghcr.io
        run: |
          sudo podman tag "gardenlinux/$target:today" "ghcr.io/gardenlinux/gardenlinux/$target:today"
          sudo podman tag "gardenlinux/$target:today" "ghcr.io/gardenlinux/gardenlinux/$target:$GITHUB_SHA"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/$target:today"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/$target:$GITHUB_SHA"
