name: build garden linux container
on:
  workflow_call:
env:
  IMAGE_NAME: gardenlinux/integration-test
jobs:
  build_container:
    name: make container
    runs-on: ec2-gardenlinux-amd64
    steps:
      - uses: actions/checkout@v3
      
      - name: make packagebuild container (all flavors, since they built up on each other)
        run: make --directory=container build-packagebuild

  upload_container:
    name: upload container
    runs-on: ec2-gardenlinux-amd64
    strategy:
      matrix:
        flavor: [ -go, -lkm, '' ]
    steps:
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u $ --password-stdin

      - name: Set VERSION from garden-version
        run: echo "VERSION=$(bin/garden-version)" >> $GITHUB_ENV
      
      - name: Set VERSION_DATE from garden-version
        run: echo "VERSION_DATE=$(bin/garden-version --date)" >> $GITHUB_ENV

      - name: Set VERSION_FULL from garden-version
        run: echo "VERSION_FULL=$(bin/garden-version --major).$(bin/garden-version --minor)" >> $GITHUB_ENV

      - name: upload packagebuild container to ghcr.io
        run: |
          sudo podman tag "gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION }}" "ghcr.io/gardenlinux/gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION }}"
          sudo podman tag "gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION_DATE }}" "ghcr.io/gardenlinux/gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION_DATE }}"
          sudo podman tag "gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION_FULL }}" "ghcr.io/gardenlinux/gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION_FULL }}"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION }}"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION_DATE }}"
          sudo podman push "ghcr.io/gardenlinux/gardenlinux/packagebuild${{ matrix.target }}:${{ env.VERSION_FULL }}"
