name: build garden linux container
on:
  workflow_call:
env:
  IMAGE_NAME: gardenlinux/integration-test
jobs:
  build_container:
    name: make container
    runs-on: ec2-gardenlinux-amd64
    steps:
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u $ --password-stdin

      - name: make and upload all packagebuild container flavors
        run: GHCR_UPLOAD=1 make --directory=container build-packagebuild
